### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Treverix** [olivere/iterm2-imagetools#1]
I'm don't know golang and I'm stuck. I've installed go with homebrew and executing the install command leads to this error message.

    ➜  go install github.com/olivere/iterm2-imagetools/cmd/imgls
    can't load package: package github.com/olivere/iterm2-imagetools/cmd/imgls: cannot find package "github.com/olivere/iterm2-imagetools/cmd/imgls" in any of:
	/usr/local/Cellar/go/1.6.2/libexec/src/github.com/olivere/iterm2-imagetools/cmd/imgls (from $GOROOT)
	($GOPATH not set)

What did I miss?

**Comment by olivere** [comment]
You probably need to set the `GOPATH` environment variable. Go will manage all its libraries, source code, and binaries below that path. Think of it as a workspace. E.g. if you set `GOPATH=$HOME/gocode`, go will install binaries to `$HOME/gocode/bin`, source code below `$HOME/gocode/src` and so on. See [here](https://golang.org/doc/code.html#GOPATH) for details.

HTH.

**Comment by Treverix** [comment]
It didn't help. I've set $GOPATH. Follow the installation instruction, go looks for the package in the cellar, not in the internet. I'm still lost. My iterm2 already had imgcat (by default?) but no imgls. That's why I try to install it from sources. Which doesn't work somehow.

    ➜  ~ echo $GOPATH
    /Users/myself/gocode
    ➜  ~ go install github.com/olivere/iterm2-imagetools/cmd/imgls
    can't load package: package github.com/olivere/iterm2-imagetools/cmd/imgls: cannot find package "github.com/olivere/iterm2-imagetools/cmd/imgls" in any of:
	/usr/local/Cellar/go/1.6.2/libexec/src/github.com/olivere/iterm2-imagetools/cmd/imgls (from $GOROOT)
	/Users/myself/gocode/src/github.com/olivere/iterm2-imagetools/cmd/imgls (from $GOPATH)

**Comment by olivere** [comment]
I'm sorry. Try:

```go
// Download, compile, and install imgls into $GOPATH/bin
$ go get -u github.com/olivere/iterm2-imagetools/cmd/imgls

// or: to install all binaries the package provides into $GOPATH/bin (`imgls` and `imgcat`)
$ go get -u github.com/olivere/iterm2-imagetools/cmd/...
```

I will fix the README. I think [this blog post](http://gowithconfidence.tumblr.com/post/118493925546/getting-started-with-go-workspaces) summarizes it well.

Sorry for the confusion.

**Comment by Treverix** [comment]
Thanks! The first command worked like a charm!

**Comment by LoganDark** [comment]
replace `install` with `get -u`
