### ISSUE TITLE
imgcat and imgls cannot work on centos ?

### ISSUE THREAD

**Issue by sowhyim** [olivere/iterm2-imagetools#4]

**Comment by sowhyim** [comment]
i have installed imgcat and imgls. but i cannot use it to view any png

**Comment by olivere** [comment]
As stated in the README, these programs only work if you use [iTerm2](https://www.iterm2.com/), which currently is available on macOS only.

**Comment by thomasmerz** [comment]
But it (should) work(s) fine on all my linux distros (openSUSE, Ubuntu) when connected via `ssh` from my Macbook's iTerm2 😄  

BTW: What's the difference to [official imgcat](https://iterm2.com/utilities/imgcat) or what makes your implementation "better"? I know bash very well, but I never dealed with go so far.
