### ISSUE TITLE
updated go installation method.

### ISSUE THREAD

**Issue by bdmorin** [olivere/iterm2-imagetools#7]
I recently tried this per the readme.
```
> GO111MODULE=on go get -u github.com/olivere/iterm2-imagetools/cmd/imgcat                                                                  7.8s  Thu May 19 18:23:23 2022
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
❯ go version                                                                                                                                       go version go1.18.2 darwin/amd64
```

So I did this, and it worked.

```
GO111MODULE=on go install  github.com/olivere/iterm2-imagetools/cmd/imgcat@latest
```

**Comment by leekyungmoon** [comment]
Despite I executed the command above, only blank image is returented.

**Comment by olivere** [comment]
@leekyungmoon I think iTerm2 now [comes with their own tools for `imgcat` and `imgls`](https://iterm2.com/documentation-images.html). At least in my iTerm 2 installation, I see bash scripts in `$HOME/.iterm2/imgcat` and `$HOME/.iterm2/imgls` (I don't know how they ended there tbh), which are also aliases in my environment.

```sh
$ type imgcat
imgcat is an alias for /Users/oliver/.iterm2/imgcat
```

So while the installation with recent versions of Go is (I will fix it and update the README):

```sh
go install github.com/olivere/iterm2-imagetools/cmd/imgcat@latest
go install github.com/olivere/iterm2-imagetools/cmd/imgls@latest
```

Maybe you're _thinking_ you use these binaries, while you're actually using [these bash scripts](https://iterm2.com/documentation-images.html).
